### PR TITLE
Location 1 PF coils don't work if there is no CS

### LINKED ISSUE #1442: Location 1 PF coils don't work if there is no CS
In GitLab by @pc6783 on Oct 28, 2021, 15:09

I got this email from a PROCESS user at PPPL:

>  Presently, if any type-1 coils are included in the PF coil model and there is no central solenoid current, the peakb subroutine in pfcoil.f90 will find a zero peak magnetic field at the location of the type-1 coils, which will subsequently cause an error when running them through the superconductor models (which don't work for a zero background field). This can be fixed by adjusting the logic in the series of if/else statements in peakb (lines 1489-1497 of pfcoil.f90 in the develop branch).

### PR DESCRIPTION
**Pull request by ajpearcey**
closes #1442

### CODE REVIEW

**Review by jonmaddock — CHANGES_REQUESTED** [review]
Can you either rebase this into a single commit or separate into the bug fix and error message addition to reduce the churn for this PR please. Otherwise fine.

**Comment by ajpearcey** [comment]
I've rebased and collapsed the new changes into one commit. Let know if this is what you had in mind.

**Comment by jonmaddock** [comment]
@ajpearcey I'm happy with the changes, but please resolve the conflicts.

**Comment by ajpearcey** [comment]
Im dumb, so ill just bin the PR and start again. It'll be easier.

**Comment by ajpearcey** [comment]
this is now superseded by #3396

**Pull request closed without merging**
