### PR TITLE
Collate cost models

### PR DESCRIPTION
**Pull request by je-cook**
## Description

Collates cost models into one interface and does a bit of cleanup while I was there

## Checklist

I confirm that I have completed the following checks:

- [ ] I have justified any large differences in the regression tests caused by this pull request in the comments.
- [ ] I have added new tests where appropriate for the changes I have made.
- [ ] If I have had to change any existing unit or integration tests, I have justified this change in the pull request comments.
- [ ] If I have made documentation changes, I have checked they render correctly.
- [ ] I have added documentation for my change, if appropriate.

### CODE REVIEW

**Comment by je-cook** [comment]
@j-a-foster if you want to do anymore removals here feel free. I dunno how access works on forks but let me know if you have problems and i'll fix it

**Comment by je-cook** [comment]
As far as I can work out its not possible to inject the custom cost model while using either the `main` function or the `Process` class (therefore from the cli). 

Is there any preference about how this could be done/if it needs to be done? 
Current options as I see it if something is done to specify the python class to import:

1) add another command line arg
2) add a variable to the inputfile
3) leave it as is and specification of a custom model requires injection through python (and initialisation of either `VaryRun` or `SingleRun`.

For point 3 my last commit unifies the running interface between `VaryRun` and `SingleRun`. 

Let me know thoughts and I can modify as needed.

**Comment by jonmaddock** [comment]
@timothy-nunn can you review this please? Thanks.

**Review by timothy-nunn — APPROVED** [review]
Confirmed this does not change the running of SingleRun or VaryRun or change any of the `large-tokamak` values.

**Comment by timothy-nunn** [comment]
@j-a-foster have you used this interface yet, and do you have any insights on how easy it is to use custom cost models?

**Comment by j-a-foster** [comment]
@timothy-nunn I've created an MR in the cost model repo that reflects the changes made here and checked that it works. Currently the only example is in the private cost model repo but we could create an example in this repo of how a user can set up their own custom cost model to work with PROCESS.

**Pull request merged**
